site_name: Raphdf201 | Shapez 2 docs
nav:
  - Home: index.md
  - Specifics:
    - Connector data: connectorData.md
    - Rendering: rendering.md
    - Simulation: simulation.md
    - Side upgrades: sideUpgrades.md
    - Toolbar locator: toolbar.md
  - Official: official.md
  - About: about.md
