site_name: Raphdf201 | Shapez 2 docs
nav:
  - Home: index.md
  - Specifics:
      - Connector data: connectorData.md
      - Rendering: rendering.md
      - Simulation: simulation.md
      - Side upgrades: sideUpgrades.md
      - Toolbar locator: toolbar.md
  - Assemblies:
    - Core.Localization: dll/corelocalization.md
    - Game.Content: dll/gamecontent.md
    - Game.Orchestration: dll/gameorchestration.md
  - Official: official.md
  - Mod ideas: modIdeas.md
  - Reference mods: referenceMods.md
  - About: about.md
